test(e2e): use underscore instead of hyphens in build identifiers (#1673)
BATCH_SPEC_VALIDATION_ERROR: BatchSpec has invalid values..
Build Identifiers customized-env,multi-env-app,multi-svc-app,app-with-domain
must contain only alphanumeric characters and underscores and be less than 128 characters in length.


_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._