test(e2e): use underscore instead of hyphens in build identifiers
BATCH_SPEC_VALIDATION_ERROR: BatchSpec has invalid values..
Build Identifiers customized-env,multi-env-app,multi-svc-app,app-with-domain
must contain only alphanumeric characters and underscores and be less than 128 characters in length.