Enable verbose error message for credential issues
Before the change:
```
$ env -i AWS_DEFAULT_REGION=us-west-1 ./bin/local/archer project ls
Error: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

After the change:
```
env -i AWS_DEFAULT_REGION=us-west-1 ./bin/local/archer project ls
Error: NoCredentialProviders: no valid providers in chain
caused by: EnvAccessKeyNotFound: failed to find credentials in the environment.
SharedCredsLoad: failed to load profile, .
EC2RoleRequestError: no EC2 instance role found
caused by: RequestError: send request failed
caused by: Get http://169.254.169.254/latest/meta-data/iam/security-credentials/: dial tcp 169.254.169.254:80: connect: host is down
```

Fixes #163.