chore(integ): make env integ error msg more helpful (#4110)
Applied only to the env integ tests first. Typical example for anything fails will be like

### Example 1: Parameter name changed
```
--- FAIL: TestEnvStack_Template (0.08s)
    --- FAIL: TestEnvStack_Template/generate_template_with_embedded_manifest_file_with_container_insights_and_imported_certificates_and_advanced_access_logs (0.01s)
        /Users/penghaoh/Work/PRIVATE-amazon-ecs-archer/internal/pkg/deploy/cloudformation/stack/env_integration_test.go:466: 
            	Error Trace:	/Users/penghaoh/Work/PRIVATE-amazon-ecs-archer/internal/pkg/deploy/cloudformation/stack/env_integration_test.go:466
            	            				/Users/penghaoh/Work/PRIVATE-amazon-ecs-archer/internal/pkg/deploy/cloudformation/stack/env_integration_test.go:447
            	            				/Users/penghaoh/Work/PRIVATE-amazon-ecs-archer/internal/pkg/deploy/cloudformation/stack/env_integration_test.go:316
            	Error:      	Not equal: 
            	            	expected: map[string]interface {}{"ALBWorkloads":map[string]interface {}{"Type":"String"}, "Aliases":map[string]interface {}{"Type":"String"}, "AppDNSDelegationRole":map[string]interface {}{"Type":"String"}, "AppDNSName":map[string]interface {}{"Type":"String"}, "AppName":map[string]interface {}{"Type":"String"}, "CreateHTTPSListener":map[string]interface {}{"AllowedValues":[]interface {}{true, false}, "Type":"String"}, "CreateInternalHTTPSListener":map[string]interface {}{"AllowedValues":[]interface {}{true, false}, "Type":"String"}, "EFSWorkloads":map[string]interface {}{"Type":"String"}, "EnvironmentName":map[string]interface {}{"Type":"String"}, "InternalALBWorkloads":map[string]interface {}{"Type":"String"}, "NATWorkloads":map[string]interface {}{"Type":"String"}, "ServiceDiscoveryEndpoint":map[string]interface {}{"Type":"String"}, "ToolsAccountPrincipalARN":map[string]interface {}{"Type":"String"}}
            	            	actual  : map[string]interface {}{"ALBWorkloads":map[string]interface {}{"Type":"String"}, "Aliases":map[string]interface {}{"Type":"String"}, "AppDNSDelegationRole":map[string]interface {}{"Type":"String"}, "AppDNSName":map[string]interface {}{"Type":"String"}, "AppName1":map[string]interface {}{"Type":"String"}, "CreateHTTPSListener":map[string]interface {}{"AllowedValues":[]interface {}{true, false}, "Type":"String"}, "CreateInternalHTTPSListener":map[string]interface {}{"AllowedValues":[]interface {}{true, false}, "Type":"String"}, "EFSWorkloads":map[string]interface {}{"Type":"String"}, "EnvironmentName":map[string]interface {}{"Type":"String"}, "InternalALBWorkloads":map[string]interface {}{"Type":"String"}, "NATWorkloads":map[string]interface {}{"Type":"String"}, "ServiceDiscoveryEndpoint":map[string]interface {}{"Type":"String"}, "ToolsAccountPrincipalARN":map[string]interface {}{"Type":"String"}}
            	            	
            	            	Diff:
            	            	--- Expected
            	            	+++ Actual
            	            	@@ -13,3 +13,3 @@
            	            	  },
            	            	- (string) (len=7) "AppName": (map[string]interface {}) (len=1) {
            	            	+ (string) (len=8) "AppName1": (map[string]interface {}) (len=1) {
            	            	   (string) (len=4) "Type": (string) (len=6) "String"
            	Test:       	TestEnvStack_Template/generate_template_with_embedded_manifest_file_with_container_insights_and_imported_certificates_and_advanced_access_logs
            	Messages:   	Comparing "Parameters"
FAIL
FAIL	github.com/aws/copilot-cli/internal/pkg/deploy/cloudformation/stack	0.558s
FAIL
```

### Example 2: Resource missing in the expected template
```
--- FAIL: TestEnvStack_Template (0.12s)
    --- FAIL: TestEnvStack_Template/generate_template_with_embedded_manifest_file_with_container_insights_and_imported_certificates_and_advanced_access_logs (0.02s)
        /Users/penghaoh/Work/PRIVATE-amazon-ecs-archer/internal/pkg/deploy/cloudformation/stack/env_integration_test.go:464: 
            	Error Trace:	/Users/penghaoh/Work/PRIVATE-amazon-ecs-archer/internal/pkg/deploy/cloudformation/stack/env_integration_test.go:464
            	            				/Users/penghaoh/Work/PRIVATE-amazon-ecs-archer/internal/pkg/deploy/cloudformation/stack/env_integration_test.go:454
            	            				/Users/penghaoh/Work/PRIVATE-amazon-ecs-archer/internal/pkg/deploy/cloudformation/stack/env_integration_test.go:316
            	Error:      	Should be true
            	Test:       	TestEnvStack_Template/generate_template_with_embedded_manifest_file_with_container_insights_and_imported_certificates_and_advanced_access_logs
            	Messages:   	"NatGateway1Attachment" does not exist in the expected template
FAIL
FAIL	github.com/aws/copilot-cli/internal/pkg/deploy/cloudformation/stack	1.078s
FAIL
```

### Example 3: Resource config changed
```
--- FAIL: TestEnvStack_Template (0.08s)
    --- FAIL: TestEnvStack_Template/generate_template_with_embedded_manifest_file_with_container_insights_and_imported_certificates_and_advanced_access_logs (0.01s)
        /Users/penghaoh/Work/PRIVATE-amazon-ecs-archer/internal/pkg/deploy/cloudformation/stack/env_integration_test.go:466: 
            	Error Trace:	/Users/penghaoh/Work/PRIVATE-amazon-ecs-archer/internal/pkg/deploy/cloudformation/stack/env_integration_test.go:466
            	            				/Users/penghaoh/Work/PRIVATE-amazon-ecs-archer/internal/pkg/deploy/cloudformation/stack/env_integration_test.go:454
            	            				/Users/penghaoh/Work/PRIVATE-amazon-ecs-archer/internal/pkg/deploy/cloudformation/stack/env_integration_test.go:316
            	Error:      	Not equal: 
            	            	expected: map[string]interface {}{"Metadata":map[string]interface {}{"aws:copilot:description":"An ECS cluster to group your services"}, "Properties":map[string]interface {}{"CapacityProviders":[]interface {}{"FARGATE", "FARGATE_SPOT"}, "ClusterSettings":[]interface {}{map[string]interface {}{"Name":"containerInsights", "Value":"enabled"}}, "Configuration":map[string]interface {}{"ExecuteCommandConfiguration":map[string]interface {}{"Logging":"DEFAULT"}}}, "Type":"AWS::ECS::Cluster"}
            	            	actual  : map[string]interface {}{"Metadata":map[string]interface {}{"aws:copilot:description":"An ECS cluster to group your services"}, "Properties":map[string]interface {}{"CapacityProviders":[]interface {}{"FARGATE", "FARGATE_SPOT"}, "ClusterSettings":[]interface {}{map[string]interface {}{"Name":"containerInsights", "Value":"disabled"}}, "Configuration":map[string]interface {}{"ExecuteCommandConfiguration":map[string]interface {}{"Logging":"DEFAULT"}}}, "Type":"AWS::ECS::Cluster"}
            	            	
            	            	Diff:
            	            	--- Expected
            	            	+++ Actual
            	            	@@ -12,3 +12,3 @@
            	            	     (string) (len=4) "Name": (string) (len=17) "containerInsights",
            	            	-    (string) (len=5) "Value": (string) (len=7) "enabled"
            	            	+    (string) (len=5) "Value": (string) (len=8) "disabled"
            	            	    }
            	Test:       	TestEnvStack_Template/generate_template_with_embedded_manifest_file_with_container_insights_and_imported_certificates_and_advanced_access_logs
            	Messages:   	Comparing "Cluster"
FAIL
FAIL	github.com/aws/copilot-cli/internal/pkg/deploy/cloudformation/stack	0.518s
FAIL
```

Note that if there are multiple mismatches in the template, developers can address these issues one by one until everything is good.


By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the Apache 2.0 License.